### ISSUE TITLE
Expose Prometheus client

### ISSUE THREAD

**Issue by fhemberger** [sanity-io/promking#1]
It would be nice to expose the underlying Prometheus client in hapi and Express, so users can add custom application metrics as well.

Example for hapi:
```js
server.decorate('server', 'prometheus', client);
...
const counter = new server.prometheus.Counter({ name: 'metric_name', help: 'metric_help' });
counter.inc();
```

**Comment by rexxars** [comment]
That sounds like a good idea. Do you feel like taking a stab at creating a pull request for this?
